language: ruby
cache: bundler
sudo: false
rvm: 2.3

install: script/bootstrap
script: script/cibuild

branches:
  only:
    - master

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variabl
  keep-history: true
  local-dir: _site
  target-branch: gh-pages
  on:
     branch: master
